version: '3.9'
services:
  db:
    build: postgresql
    image: fitness_postgres:1.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vvit79Ss79
      POSTGRES_DB: postgres
    networks:
      - fitness_ntwrk

  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    networks:
     - fitness_ntwrk

  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  fitness:
    build: fitness
    image: fitness_fitness:1.0
    networks:
      - fitness_ntwrk

  proxy:
    build: proxy
    image: fitness_proxy:1.0
    ports:
      - "80:80"
    networks:
     - fitness_ntwrk

networks:
  fitness_ntwrk:
    name: fitness_ntwrk